### ISSUE TITLE
zombied phantomjs processes

### ISSUE THREAD

**Issue by weisjohn** [weisjohn/sleepyhollow-node#3]
after debugging a few things, I found a ton of zombied processes days later:

```
$ ps aux | grep phantomjs
jweis           49145   0.0  0.4  3772256  59448   ??  S    Sat02AM   1:50.23 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           49045   0.0  0.3  3770276  58056   ??  S    Sat02AM   1:49.42 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           49021   0.0  0.4  3771368  58896   ??  S    Sat02AM   1:48.69 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48998   0.0  0.4  3771388  59060   ??  S    Sat02AM   1:49.31 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48975   0.0  0.4  3772348  58948   ??  S    Sat02AM   1:47.91 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48953   0.0  0.4  3770380  59008   ??  S    Sat02AM   1:48.40 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48873   0.0  0.3  3721140  42868   ??  S    Sat02AM   1:50.17 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48848   0.0  0.3  3721140  43136   ??  S    Sat02AM   1:50.21 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48826   0.0  0.3  3721140  43352   ??  S    Sat02AM   1:49.34 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48804   0.0  0.3  3721140  42860   ??  S    Sat02AM   1:49.41 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48782   0.0  0.3  3722132  42872   ??  S    Sat02AM   1:50.28 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48759   0.0  0.3  3721140  42756   ??  S    Sat02AM   1:50.01 phantomjs node_modules/sleepyhollow-phantom/test.js
jweis           48734   0.0  0.3  3722196  43188   ??  S    Sat02AM   1:50.73 phantomjs node_modules/sleepyhollow-phantom/test.js
```

seems like a problem

**Comment by weisjohn** [comment]
building a dummy crash example:

```
$ node examples/crash.js 
/Users/jweis/mysrc/weisjohn/sleepyhollow-node/examples/crash.js:10
    throw new Error("some sort of error");
          ^
Error: some sort of error
    at null._onTimeout (/Users/jweis/mysrc/weisjohn/sleepyhollow-node/examples/crash.js:10:11)
    at Timer.listOnTimeout (timers.js:110:15)
```

then afterward, we see:

```
$ ps aux | grep phantom
jweis           81809   0.3  0.0  2425192    432 s000  R+    1:55AM   0:00.00 grep phantom
jweis           81790   0.0  0.3  3731620  47468 s000  S     1:55AM   0:00.46 phantomjs ./node_modules/sleepyhollow-phantom/examples/throws.js
```
